FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./


# Install all dependencies (including dev dependencies)
RUN npm ci
RUN apk add --no-cache bash

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

# Change ownership of the app directory
RUN chown -R nodejs:nodejs /app
USER nodejs

# Start in development mode
CMD ["npm", "run", "dev"] 